lookwhosstreaming/lookwhosstreaming/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('admin/login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('streams.urls')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lookwhosstreaming/streams/urls.py
from django.urls import path
from .views import *

app_name = "streams"

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('top-charts/', TopChart.as_view(), name="top_chart"),
    path('admin/', Admin.as_view(), name="admin"),

    # Streams
    path('admin/streams/', StreamList.as_view(), name="stream_list"),
    path('admin/streams/create', StreamCreate.as_view(), name="stream_create"),
    path('admin/streams/<pk>/', StreamDetail.as_view(), name="stream_detail"),
    path('admin/streams/<pk>/update', StreamUpdate.as_view(), name="stream_update"),
    path('admin/streams/<pk>/delete', StreamDelete.as_view(), name="stream_delete"),


    # Streamers
    path('admin/streamers/', StreamerList.as_view(), name="streamer_list"),
    path('admin/streamers/create', StreamerCreate.as_view(), name="streamer_create"),
    path('admin/streamers/<pk>/', StreamerDetail.as_view(), name="streamer_detail"),
    path('admin/streamers/<pk>/update', StreamerUpdate.as_view(), name="streamer_update"),
    path('admin/streamers/<pk>/delete', StreamerDelete.as_view(), name="streamer_delete"),

    # API Accounts
    path('admin/api-accounts/', APIAccountList.as_view(), name="apiaccount_list"),
    path('admin/api-accounts/create', APIAccountCreate.as_view(), name="apiaccount_create"),
    path('admin/api-accounts/<pk>/', APIAccountDetail.as_view(), name="apiaccount_detail"),
    path('admin/api-accounts/<pk>/update', APIAccountUpdate.as_view(), name="apiaccount_update"),
    path('admin/api-accounts/<pk>/delete', APIAccountDelete.as_view(), name="apiaccount_delete")
]

lookwhosstreaming/streams/forms.py
from django import forms
from .models import *


# Custom Fields

class AccountModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.name_with_platform


# Forms
class AddScheduleForm(forms.Form):
    schedule = forms.FileField(widget=forms.FileInput(attrs={'accept': '.csv, .xlsx'}), label="Upload File")
    
class BulkAddStreamersForm(forms.Form):
    schedule = forms.FileField(widget=forms.FileInput(attrs={'accept': '.csv, .xlsx'}), label="Upload File")

class StreamForm(forms.ModelForm): 
    host = AccountModelChoiceField(queryset=Account.objects.all().order_by('streamer'))
    start_time = forms.DateTimeField(input_formats=["%m/%d/%Y %I:%M%p"], widget=forms.widgets.DateTimeInput(attrs={'placeholder': "Example: 1/29/2020 10:00pm"}))

    class Meta:
        model = Stream
        fields = ['host', 'broadcast_id', 'url', 'start_time']

class StreamerForm(forms.Form):
    streamer_name = forms.CharField(max_length=50)
    instagram_username = forms.CharField(max_length=50, required=False)
    twitch_username = forms.CharField(max_length=50, required=False)
    youtube_username = forms.CharField(max_length=50, required=False)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False)


class APIAccountForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta: 
        model = APIAccount
        fields = '__all__'

lookwhosstreaming/streams/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, Q
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from datetime import datetime, date, timedelta

from .forms import *
from .models import *
from .handler import *

# Create your views here.

class Home(View):

    def get(self, request):

        # Context Variables
        streams = Stream.objects.all()
        live_streams = Stream.objects.filter(live=True)
        categories = [Category.objects.get_or_create(name=category)[0] for category in ['Music', 'Influencers', 'Gamers']]
        platforms = [Platform.objects.get_or_create(name=platform)[0] for platform in ['Instagram', 'YouTube', 'Twitch']]
        dates = [(date.today() + timedelta(days=x)) for x in range(-10, 11)]

        # Filters
        # Platform Filter
        if platform_query := request.GET.get('platform'):
            streams = streams.filter(platform__name=platform_query)
            live_streams = live_streams.filter(platform__name=platform_query)
        
        # Category Filter
        if category_query := request.GET.get('category'):
            streams = streams.filter(host__streamer__category__name=category_query)
            live_streams = live_streams.filter(host__streamer__category__name=category_query)

        # Date Filter
        if date_query := request.GET.get('date'):
            try:
                date_query = datetime.strptime(date_query, '%m-%d-%Y').date()
                streams = streams.filter(start_time__date=date_query)
                live_streams = live_streams.filter(start_time__date=date_query)
            except ValueError:
                print('Stream didn\'t work')
        else:
            # Show only streams that are live or haven't yet begun.
            streams = Stream.objects.filter(start_time__date=date.today()) | Stream.objects.filter(live = True) 

        context = {
            'platforms': platforms,
            'categories': categories,
            'dates': dates,
            'streams': streams,
            'live_streams': live_streams,
        }

        return render(request, 'streams/home/home_schedule.html', context)

class TopChart(View):

    def get(self, request):
        # Context Variables
        streams = Stream.objects.all().order_by('-score')
        categories = [Category.objects.get_or_create(name=category)[0] for category in ['Music', 'Influencers', 'Gamers']]
        platforms = [Platform.objects.get_or_create(name=platform)[0] for platform in ['Instagram', 'YouTube', 'Twitch']]

        # Filters
        # Platform Filter
        if platform_query:= request.GET.get('platform'):
            platform = Platform.objects.get(name__iexact=platform_query)
            streams = streams.filter(host__platform=platform)

        # Category Filter
        if category_query:= request.GET.get('category'):
            category = Category.objects.get(name__iexact=category_query)
            streams = streams.filter(host__streamer__category=category)
        
        # Time Filter
        if time_query := request.GET.get('time'):
            if time_query == "all-time":
                pass
            elif time_query == 'today':
                streams = streams.filter(start_time__day=datetime.now().day, start_time__year=datetime.now().year, start_time__month=datetime.now().month)
            elif time_query in {"7", "30"}:
                days = int(time_query)
                start_date = datetime.now() - timedelta(days=days)
                streams = streams.filter(start_time__gt=start_date)
            else:
                streams = streams.filter(start_time__day=datetime.now().day, start_time__year=datetime.now().year)
        else:
            time_query = None

        # Top 100 streams only
        streams = streams[:100]


        context = {
            'streams': streams,
            'platforms': platforms,
            'categories': categories,
            'active_platform': platform_query,
            'active_category': category_query,
            'time_query': time_query,
        }

        return render(request, 'streams/home/home_top_chart.html', context)




# Admin Pages ------------------------------------------------------------------


class Admin(LoginRequiredMixin, View):

    def get(self, request):
        streams = Stream.objects.all()

        if active_platform := request.GET.get('platform'):
            streams = streams.filter(platform__name=active_platform)

        if active_field := request.GET.get('field'):
            if active_field in {'host', 'platform'}:
                streams = streams.order_by(f'{active_field}__name')
            elif active_field in {'live', 'score'}:
                streams = streams.order_by(f'-{active_field}')
            else:
                streams = streams.order_by(f'{active_field}')

        platforms = Platform.objects.all()
        stream_fields = [field for field in Stream._meta.fields if field.verbose_name not in {'ID', 'shady', 'Likes Data', 'Viewer Data', 'Cover Frame'}]

        context = {
            'platforms': platforms,
            'streams': streams,
            'stream_fields': stream_fields,
            'active_platform': active_platform,
            'active_field': active_field,
        }

        return render(request, 'streams/admin/admin.html', context)


# Streamers --------------------------------------------------------------------
class StreamerList(LoginRequiredMixin, ListView):
    model = Streamer
    template_name = 'streams/admin/streamer/streamer_list.html'


class StreamerCreate(LoginRequiredMixin, View):
    def get(self, request):
        form = StreamerForm()
        platforms = Platform.objects.all()
        categories = Category.objects.all()
        context = {
            'form': form,
            'platforms': platforms,
            'categories': categories
        }
        return render(request, 'streams/admin/streamer/streamer_create.html', context)

    def post(self, request):
        if 'upload_file' in request.POST:
            successes, errors = process_watch_list_csv(request.FILES['csv'].read())
            print(f'Errors: {errors}')
            print(f'Successes: {successes}')
            return redirect('streams:streamer_create')
        else:
            form = StreamerForm(request.POST)
            if form.is_valid():
                # Get streamer category
                category_id = request.POST.get('category')
                category = Category.objects.get(id=category_id) if category_id else None
                if category:
                    streamer = Streamer.objects.create(name=form.cleaned_data['streamer_name'], category=category)
                else:
                    streamer = Streamer.objects.create(name=form.cleaned_data['streamer_name'])
                for platform in Platform.objects.all():
                    if request.POST.get(f'{platform.name.lower()}_username'):
                        username = request.POST.get(f'{platform.name.lower()}_username')
                        Account.objects.create(name = strip_username(username), platform = platform, streamer = streamer)
                return redirect('streams:streamer_list')


class StreamerUpdate(LoginRequiredMixin, View):

    def get(self, request, pk):

        INITIAL_VALUES = {}
        streamer = Streamer.objects.get(pk=pk)
        INITIAL_VALUES['streamer_name'] = streamer.name

        for platform in Platform.objects.all():
            if account := streamer.account_set.filter(platform=platform):
                INITIAL_VALUES[f'{platform.name.lower()}_username'] = account[0].name

        INITIAL_VALUES['category'] = streamer.category

        form = StreamerForm(initial=INITIAL_VALUES)
        return render(request, 'streams/admin/streamer/streamer_update.html', {'form': form, 'streamer': streamer})

    def post(self, request, pk):
        form = StreamerForm(request.POST)
        if form.is_valid():

            # Get streamer object from view
            streamer = Streamer.objects.get(id=pk)

            # Get streamer category
            category_id = request.POST.get('category')
            category = Category.objects.get(id=category_id) if category_id else None

            # Update streamer data
            if category:
                streamer.category = category
                streamer.name = form.cleaned_data['streamer_name']
            else:
                streamer.category = None
                streamer.name = form.cleaned_data['streamer_name']
            streamer.save()

            # Update platform account data TODO: Don't let form pass empty value
            for platform in Platform.objects.all():
                if request.POST.get(f'{platform.name.lower()}_username'):
                    account_name = request.POST.get(f'{platform.name.lower()}_username')
                    account, account_create = streamer.account_set.get_or_create(platform=platform)
                    account.name = account_name
                    account.save()
        else:
            print(form.errors)
        return redirect('streams:streamer_list')


class StreamerDetail(LoginRequiredMixin, DetailView):
    model = Streamer
    template_name = 'streams/admin/streamer/streamer_detail.html'


class StreamerDelete(LoginRequiredMixin, View):

    def get(self, request, pk):
        api_account = Streamer.objects.get(pk=pk)
        api_account.delete()
        return redirect('streams:streamer_list')

# API Accounts -----------------------------------------------------------------


class APIAccountList(LoginRequiredMixin, ListView):
    model = APIAccount
    template_name = 'streams/admin/apiaccount/apiaccount_list.html'


class APIAccountDetail(LoginRequiredMixin, DetailView):
    model = APIAccount

lookwhosstreaming/streams/templates/streams/admin/apiaccount/apiaccount_create.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<li><a href="{% url 'streams:apiaccount_list' %}" class="back">Back</a></li>
{% endblock %}

{% block main %}
<div class="admin">
  <div class="api-accounts">
    <div class="admin-header">
      <h1>Add API Account</h1>
    </div>

    <!-- Bulk Streamer Form -->
    <form method="POST" class="admin-form" id="streamer-csv-form" enctype="multipart/form-data">
      {% csrf_token %}
      <h2>Bulk Add API Accounts</h2>
      <p class="field-group">
        <label for="csv">Upload CSV File</label>
        <input type="file" name="csv" accept=".csv" id="id_csv">
      </p>
      <button type="submit" name="upload_file">Upload File</button>
    </form>

    <form class="admin-form" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label }}{% if field.field.required %}*{% endif %}
        {{ field }}
        {% if field.errors %}
        {{ field.errors }}
        {% endif %}
      </p>
      {% endfor %}
      <button type="submit">Add Account</button>
    </form>
  </div>
</div>
{% endblock %}

lookwhosstreaming/streams/templates/streams/admin/apiaccount/apiaccount_detail.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<li><a href="{% url 'streams:apiaccount_list' %}" class="back">Back</a></li>
{% endblock %}

{% block main %}
<div class="admin">
  <div class="api-account-detail">
    <div class="admin-header">
      <h1>API Account Admin</h1>
    </div>

    <div class="admin-detail-block">
      <div class="admin-detail-block-header">
        <h2>{{ apiaccount.username }}</h2>
      </div>
      <table>
        <tr>
          <th><strong>Platform: </strong></th>
          <td>{{ apiaccount.platform }}</td>
        </tr>
        <tr>
          <th><strong>Email: </strong></th>
          <td>{{ apiaccount.email }}</td>
        </tr>
        <tr>
          <th><strong>Password: </strong></th>
          <td class="password">{{ apiaccount.password }}</td>
        </tr>
        <tr>
          <th><strong>Client ID: </strong></th>
          <td>{{ apiaccount.client_id }}</td>
        </tr>
        <tr>
          <th><strong>Auth Token: </strong></th>
          <td>{{ apiaccount.auth_token }}</td>
        </tr>
        <tr>
          <th><strong>API Key: </strong></th>
          <td>{{ apiaccount.api_key }}</td>
        </tr>
      </table>
      <p></p>
    </div>
  </div>
</div>
</div>
{% endblock %}

lookwhosstreaming/streams/templates/streams/admin/apiaccount/apiaccount_form.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<li><a href="{% url 'streams:apiaccount_list' %}" class="back">Back</a></li>
{% endblock %}

{% block main %}
<div class="admin">
  <div class="api-accounts">
    <div class="admin-header">
      <h1>Update API Account</h1>
    </div>

    <!-- API Account Form -->
    <form class="admin-form" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label }}{% if field.field.required %}*{% endif %}
        {{ field }}
        {% if field.errors %}
        {{ field.errors }}
        {% endif %}
      </p>
      {% endfor %}
      <button type="submit">{% if apiaccount %}Update{% else %}Add{% endif %} Account</button>
    </form>
  </div>
</div>
{% endblock %}

lookwhosstreaming/streams/templates/streams/admin/apiaccount/apiaccount_list.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<li><a href="{% url 'streams:admin' %}" class="back">Back</a></li>
{% endblock %}

{% block main %}
<div class="admin">
  <div class="api-accounts">
    <div class="admin-header">
      <h1>API Account Admin</h1>
    </div>

    <!-- Index Table -->
    <div class="index-list">

      <!-- Header -->
      <div class="header">
        <h2>Accounts</h2>
        <a href="{% url 'streams:apiaccount_create' %}" class="button"><i class="fas fa-plus"></i></a>
      </div>

      <!-- Table Start -->
      <div class="index-list-table">
        <div class="thead">
          <div class="row">
            <span class="data">Account</span>
            <span class="data">Platform</span>
            <span class="data"></span>
          </div>
        </div>
        <div class="tbody">
          {% if apiaccount_list %}

          {% for apiaccount in apiaccount_list %}
          <div class="row">
            <span class="data"><a href="{% url 'streams:apiaccount_detail' apiaccount.pk %}">{{ apiaccount.username }}</a></span>
            <span class="data">{{ apiaccount.platform }}</span>
            <div class="buttons">
              <a class="edit" href="{% url 'streams:apiaccount_update' apiaccount.id %}"><i class=" fas fa-pencil-alt"></i></a>
              <a class="delete" href="{% url 'streams:apiaccount_delete' apiaccount.id %}"><i class="fas fa-times"></i></a>
            </div>
          </div>
          {% endfor %}
          {% else %}
          <div class="row">
            No accounts.
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}