FLVA/base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('thank-you/', views.thank_you, name="thank_you"),
    path('faq/', views.faq, name="faq"),
    path('events/', views.events, name="events"),
    path('events/<slug:event_slug>/', views.event_detail, name="event_detail"),
    path('signup/', views.signup, name="signup")
]

FLVA/communitysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FLVA/base/models.py
from django.db import models
from django.utils.text import slugify
from datetime import date

# Create your models here.
class Post(models.Model):
    image = models.ImageField(upload_to="images/", null=True, blank=True)
    title = models.CharField(max_length=100, null=True, unique=True)
    body = models.TextField(null=True)
    display = models.BooleanField(default=False)
    pub_date = models.DateField()

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

    def contains_image(self):
        return bool(self.image)

class Contact(models.Model):
    first_name = models.CharField(max_length=20, null=True, blank=True)
    last_name = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(unique=True, null=True)
    subject = models.CharField(max_length=100, null=True)
    message = models.TextField(null=True, blank=True)

    def full_name(self):
        return f'{first_name} {last_name}'

    def __str__(self):
        return self.email

class FAQ(models.Model):
    question = models.CharField(max_length=200, null=True, help_text="Max Characters: 200", unique=True)
    answer = models.TextField(max_length=200, null=True, blank=True)
    display = models.BooleanField(default=True)

    def __str__(self):
        return self.question

class AboutSection(models.Model):
    title = models.CharField(max_length=20, null=True, blank=True)
    image = models.ImageField(upload_to="images/", null=True, blank=True)
    body = models.TextField(null=True)
    display = models.BooleanField(default=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.title

class Event(models.Model):
    image = models.ImageField(upload_to="images", null=True)
    title = models.CharField(max_length=50, null=True)
    description = models.TextField(null=True, blank=True)
    date = models.DateField(null=True)
    EVENT_TYPE_CHOICES = (
        ('In Person', 'In Person', ),
        ('Online', 'Online')
    )
    type = models.CharField(max_length=20, choices=EVENT_TYPE_CHOICES, null=True, default="Online")
    location = models.URLField(null=True, blank=True, help_text="Enter the link to the location of the event.")
    display = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def contains_image(self):
        return bool(self.image)

    def has_passed(self):
        return date.today() > self.date


    @property
    def slug(self):
        return slugify(self.title)

FLVA/base/forms.py
from django import forms
from .models import Contact, FAQ

class ContactForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First name'}), label='')
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Last name'}), label='')
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}), label='')
    subject = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Subject'}), label='')
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Message'}), label='')

    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'email', 'subject', 'message')

class QuestionForm(forms.ModelForm):
    class Meta:
        model = FAQ
        fields = ('question', )

class AnswerForm(forms.ModelForm):
    class Meta:
        model = FAQ
        fields = ('answer', )

class SignupForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First name'}), label='')
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Last name'}), label='')
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}), label='')
    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'email')

FLVA/base/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.utils.text import slugify
from .models import Post, Contact, FAQ, AboutSection, Event
from .forms import ContactForm, SignupForm

# Create your views here.
def index(request):
    posts = Post.objects.all()
    events = Event.objects.all()

    context = {
    'posts': posts,
    'events':events,
    }

    return render(request, 'base/index.html', context)

def about(request):
    about_sections = AboutSection.objects.all()
    context = {'about_sections': about_sections}
    return render(request, 'base/about.html', context)

def events(request):
    events = Event.objects.all()

    context = {
        'events': events,
    }

    return render(request, 'base/event-index.html', context)

def event_detail(request, event_slug):

    events = Event.objects.all()

    for event in events:
        if slugify(event.title) == event_slug:
            instance = event
            break

    context = {
        'event': instance,
    }

    return render(request, 'base/event-detail.html', context)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        form.save()
        return HttpResponseRedirect('../thank-you/')
    else:
        form = ContactForm
        context = {'form': form}
        return render(request, 'base/contact.html', context)

def faq(request):
    faqs = FAQ.objects.all()
    context = {
        'faqs':  faqs
    }
    return render(request, 'base/faq.html', context)

def thank_you(request):
    return render(request, 'base/thank-you.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        form.save()
        return HttpResponseRedirect('../thank-you/')
    else:
        form = SignupForm()
        context = {'form': form}
        return render(request, 'base/signup.html', context)

FLVA/base/templates/base/about.html
{% extends 'base.html' %}

{% block title %}About {% endblock %}

{% block main %}
<div class="about">
  <div class="hero">
    <h1 class="title">About us</h1>
  </div>
  <div class="content">
    {% for section in about_sections %}
    <div class="section">
      <h2 class="title">{{ section.title }}</h2>
      {% if section.image %}<img src="{{ section.image.url }}" alt="{{ section.title }} image">{% endif %}
      <p class="body">{{ section.body|linebreaksbr }}</p>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

FLVA/base/templates/base/contact.html
{% extends 'base.html' %}

{% block title %}Contact {% endblock %}

{% block main %}
<div class="contact">
  <div class="hero">
    <h1 class="title">Contact</h1>
  </div>
  <div class="content">
    <div class="form-area">
      <h2 class="title">Have A Question?</h2>
      <p class="subtitle">We're here to help! Fill out the form below and we'll get back to you within 24 hours.</p>
      <form  method="post">
        {% csrf_token %}
        {{ form }}
        <div class="buttons-area">
          <button class="big-button" type="submit">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>


{% endblock %}

FLVA/base/templates/base/event-detail.html
{% extends 'base.html' %}

{% block title %}{{ event.title }} {% endblock %}

{% block below_nav %}
  <ul class="breadcrumbs">
    <li><a href="{% url 'base:index' %}">Back</a></li>
  </ul>
{% endblock %}

{% block main %}
<div class="event-detail">
    <div class="block">
      {% if event.image %}<img src="{{ event.image.url }}">{% endif %}
      <div class="content">
        <h1 class="title">{{ event.title }}</h1>
        <p class="date">{{ event.date }}</p>
        <p class="description">{{ event.description|linebreaksbr }}</p>

        {% if event.type == "In Person" %}
        <div class="buttons-area">
          <a class="big-button" target="_blank" href="{{ event.location }}">Get Directions</a>
        </div>
        {% endif %}
      </div>
    </div>
</div>
{% endblock %}

{% block prefooter %}
{% endblock %}

FLVA/base/templates/base/event-index.html
{% extends 'base.html' %}

{% block title %}Events{% endblock %}

{% block main %}
<div class="events-index">
  <div class="hero">
    <h1 class="title">Events</h1>
  </div>
  {% if events %}
  <div class="events">
    {% for event in events %}
    <a href="{% url 'base:event_detail' event.slug %}" class="event">
      <img src="{{ event.image.url }}" alt="Image of event {{ event.title }}">
      <div class="text">
        <h2 class="title">{{ event.title }}</h2>
        <p class="date">{{ event.date }}</p>
          <div class="big-button">
            Learn more
          </div>
      </div>

    </a>
    {% endfor %}
  </div>
  {% else %}
  <h2>There are currently no events.</h2>
  {% endif %}
</div>
{% endblock %}

FLVA/base/templates/base/faq.html
{% extends 'base.html' %}

{% block title %}FAQ {% endblock %}

{% block main %}
<div class="faq">
  <div class="hero">
    <h1 class="title">FAQ</h1>
  </div>

  <div class="content">
    <div class="questions">
    {% for faq in faqs %}
      {% if faq.display %}
      <div class="block">
          <p class="question">{{ faq.question }}</p>
          <p class="answer">{{ faq.answer }}</p>
      </div>
      {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}

FLVA/base/templates/base/index.html
{% extends 'base.html' %}

{% block below_nav %}
  <!-- Optional Main Call to Action for new users

  </div> -->
{% endblock %}

{% block main %}
<div class="index">
  <div class="hero">
      <h1 class="title"><span>F</span>uture <span>L</span>ibrarians of <span>V</span>irgini<span>a</span></h1>
  </div>
  {% if events %}
  <a class="events-mobile-link" href="{% url 'base:events' %}">See Events</a>
  {% endif %}
  <div class="content">
    {% if posts %}
    <div class="posts">
      <p class="section-title">News</p>
      <p class="subtitle">Stay up to date on the latest community updates.</p>
      {% for post in posts %}
      <div class="post">
        <h2 class="title">{{ post.title }}</h2>
        <p class="pub-date">{{ post.pub_date }}</p>
        {% if post.image %}<img src="{{ post.image.url }}">{% endif %}
        <p class="body">{{ post.body|linebreaksbr }}</p>
      </div>
      {% endfor %}
    </div>
    {% endif %}
    {% if events %}
    <div class="events">
      <p class="section-title">Events</p>
      <p class="subtitle">See upcoming community events and get involved!</p>

      {% for event in events %}
      {% if event.has_passed %}
      {% else %}
      <a class="event" href="{% url 'base:event_detail' event.slug %}">
        <img src="{{ event.image.url }}" alt="Image relevant to the event.">
        <div class="text">
          <p class="title">{{ event.title }}</p>
          <p class="date">{{ event.date }}</p>
          <p class="cta">View</p>
        </div>
      </a>
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

FLVA/base/templates/base/signup.html
{% extends 'base.html' %}

{% block title %}Join Our Community! {% endblock %}

{% block main %}
<div class="signup">
  <h1 class="section-title">Join our community!</h1>
  <p class="subtitle">
    Go further than you ever thought you could with the help of our team by joining our community!<br><br>
    Fill out the form below to sign up and become a part of a community that's here to help.
  </p>
  <div class="form-area">
    <form method="post">
      {% csrf_token %}
      {{ form }}
      <div class="buttons-area">
        <button type="submit" class="big-button">Sign Up</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block prefooter %}
{% endblock %}

FLVA/base/templates/base/thank-you.html
{% extends 'base.html' %}

{% block title %}Thanks! {% endblock %}

{% block main %}
<div class="thank-you">
  <h1 class="title">Thanks! We'll be in touch soon.</h1>
  <a class="big-button" href="{% url 'base:index' %}">Return Home</a>
</div>
{% endblock %}
{% block prefooter %}
{% endblock %}